Create MyBigInt
dimaruso/made_2019_cpp pull request #6
Opened 2019-11-22 14:21 UTC by dimaruso

2019-11-24 11:25 UTC, smirnov-vs requested changes
привет!
есть неправильная работа с памятью, надо починить

2019-11-24 11:25 UTC, smirnov-vs commented on 06/MyBigInt.h
> +	}
какие-то функции написаны в .h, хотя они довольно большие, надо разделить интерфейс и реализацию

2019-11-24 11:25 UTC, smirnov-vs commented on 06/MyBigInt.h
> +		data(std::move(moved.data))
мув примитивных типов

2019-11-24 11:25 UTC, smirnov-vs commented on 06/MyBigInt.cpp
> +				tmp.data = std::move(newdata);
тоже мув примитивного типа

2019-11-24 12:16 UTC, dimaruso commented on 06/MyBigInt.h
> +	}
Перенес всю реализацию методов из заголовочного файла

2019-11-24 12:17 UTC, dimaruso commented on 06/MyBigInt.h
> +		data(std::move(moved.data))
Заменил на:
MyBigInt::MyBigInt(MyBigInt&& moved) :
	size(moved.size),
	sign(moved.sign),
	data(moved.data)
{
	moved.data = nullptr;
	moved.size = 0;
}

2019-11-24 12:18 UTC, dimaruso commented on 06/MyBigInt.cpp
> +				tmp.data = std::move(newdata);
Заменил везде на:
tmp.data = newdata;

2019-11-25 14:07 UTC, smirnov-vs commented
привет!
неверная работа с памятью не исправлена

2019-11-27 09:43 UTC, merged