Create Formatter
dimaruso/made_2019_cpp pull request #7
Opened 2019-12-02 11:41 UTC by dimaruso

2019-12-03 09:20 UTC, smirnov-vs requested changes

2019-12-03 09:20 UTC, smirnov-vs commented on 07/Formatter.cpp
> +			catch (...)
какое исключение ловим? надо написать

2019-12-03 09:20 UTC, smirnov-vs commented on 07/Formatter.cpp
> +			res.push_back(s[i]);
обычно юзают +=

2019-12-03 09:20 UTC, smirnov-vs commented on 07/Formatter.cpp
> +const std::string Formatter::Calc(const std::string& s, const std::vector<std::string>& _Sargs)
названия функции с маленькой буквы, надо бы подыскать более логичное название

2019-12-03 11:04 UTC, dimaruso commented on 07/Formatter.cpp
> +			res.push_back(s[i]);
Заменил push_back на +=

2019-12-03 11:05 UTC, dimaruso commented on 07/Formatter.cpp
> +const std::string Formatter::Calc(const std::string& s, const std::vector<std::string>& _Sargs)
Переименовал на format

2019-12-03 11:07 UTC, dimaruso commented on 07/Formatter.cpp
> +			catch (...)
Ловил все исключения с использования сторонней функции, но в данном случае это не нужно т.к. то, что входная строка pos будет корректна (не пуста и состоит из цифр) отслеживается ранее. Поэтому убрал блок try catch.

2019-12-04 09:09 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-12-04 09:09 UTC, smirnov-vs commented on 07/Formatter.cpp
> +const std::string Formatter::format(const std::string& s, const std::vector<std::string>& _Sargs)
`const` лишний у возвращаемой строки

2019-12-04 09:19 UTC, merged