Create MyVector
dimaruso/made_2019_cpp pull request #8
Opened 2019-12-05 15:04 UTC by dimaruso

2019-12-05 20:42 UTC, smirnov-vs requested changes

2019-12-05 20:42 UTC, smirnov-vs commented on 08/MyVector.h
> +};
а зачем пустой класс?
проще тогда уже без него

2019-12-05 20:42 UTC, smirnov-vs commented on 08/MyVector.h
> +	class Iterator : public std::iterator<std::input_iterator_tag, TypeI>
не та категория

2019-12-05 20:42 UTC, smirnov-vs commented on 08/MyVector.h
> +	std::copy(init.begin(), init.end(), data);
слева мусор, так нельзя

2019-12-05 20:42 UTC, smirnov-vs commented on 08/MyVector.h
> +	data[size_] = std::move(value);
аналогично

2019-12-05 20:42 UTC, smirnov-vs commented on 08/MyVector.h
> +	memcpy(newData, data, sizeof(value_type)*size_);
это работает не так, как ожидается от вектора

2019-12-06 13:39 UTC, dimaruso commented on 08/MyVector.h
> +};
Убрал пустой класс. В классе MyVector поставил std::allocator<T> как аллокатор по умолчанию.

2019-12-06 13:39 UTC, dimaruso commented on 08/MyVector.h
> +	class Iterator : public std::iterator<std::input_iterator_tag, TypeI>
Заменил на Bidirectional Iterator

2019-12-06 13:40 UTC, dimaruso commented on 08/MyVector.h
> +	std::copy(init.begin(), init.end(), data);
Заменил на вызов конструкторов.

2019-12-06 13:40 UTC, dimaruso commented on 08/MyVector.h
> +	data[size_] = std::move(value);
Заменил на вызов конструкторов.

2019-12-06 13:41 UTC, dimaruso commented on 08/MyVector.h
> +	memcpy(newData, data, sizeof(value_type)*size_);
Провел сравнение с вектором и добавил тестов.

2019-12-07 10:58 UTC, smirnov-vs commented on 08/MyVector.h
> +	class Iterator : public std::iterator<std::input_iterator_tag, TypeI>
мимо все равно)
вспоминаем лекцию и подбираем нужный

2019-12-07 11:01 UTC, smirnov-vs requested changes

2019-12-07 11:01 UTC, smirnov-vs commented on 08/MyVector.h
> +	value = value_type();
почему так?
от функции ожидается мув

2019-12-07 11:01 UTC, smirnov-vs commented on 08/MyVector.h
> +	for (auto i : init)
копируется в i

2019-12-07 11:01 UTC, smirnov-vs commented on 08/MyVector.h
> +		data[i] = defaultValue;
слева мусор

2019-12-07 21:24 UTC, dimaruso commented on 08/MyVector.h
> +	class Iterator : public std::iterator<std::input_iterator_tag, TypeI>
Поставил тип итератора произвольного доступа random_access_iterator_tag

2019-12-07 21:24 UTC, dimaruso commented on 08/MyVector.h
> +	value = value_type();
Заменил на мув:
alloc_.construct(data + size_++, std::move(value));

2019-12-07 21:25 UTC, dimaruso commented on 08/MyVector.h
> +	for (auto i : init)
Передаю по ссылке: for (auto& i : init)

2019-12-07 21:26 UTC, dimaruso commented on 08/MyVector.h
> +		data[i] = defaultValue;
Добавлен вызов конструктора напрямую alloc_.construct(data + i, defaultValue);

2019-12-09 08:44 UTC, smirnov-vs approved these changes
Привет!
я зачел

стоит еще помнить, что для рандом аксес итератора нужно больше методов

2019-12-09 10:15 UTC, merged